config/routes.rb
Rails.application.routes.draw do
  resources :ingredientes,
    only: [:index, :show, :create, :update, :destroy],
    path: 'ingrediente',
    defaults: { format: 'json' }
  resources :hamburguesas, only: [:index, :show, :create, :update, :destroy],
    path: 'hamburguesa',
    defaults: { format: 'json' } do
      put 'ingrediente/:ingrediente_id', to: 'hamburguesas#add_ingrediente'
      delete 'ingrediente/:ingrediente_id', to: 'hamburguesas#delete_ingrediente'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hamburguesa.rb
class Hamburguesa < ApplicationRecord
  has_and_belongs_to_many :ingredientes
end

app/models/ingrediente.rb
class Ingrediente < ApplicationRecord
  has_and_belongs_to_many :hamburguesas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  self.responder = ApiResponder
  respond_to :json

  skip_before_action :verify_authenticity_token
end

app/controllers/hamburguesas_controller.rb
class HamburguesasController < ApplicationController
  before_action :set_hamburguesa, only: [:show, :update, :destroy]

  def index
    @hamburguesas = Hamburguesa.all
    respond_with @hamburguesas
  end

  def show
    respond_with @hamburguesa
  end

  def create
    @hamburguesa = Hamburguesa.new(hamburguesa_params)
    if @hamburguesa.save
      respond_with @hamburguesa, status: :created
    else
      respond_with @hamburguesa.errors, status: :unprocessable_entity
    end
  end

  def update
    if @hamburguesa.update(hamburguesa_params)
      respond_with @hamburguesa, status: :ok
    else
      respond_with @hamburguesa.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @hamburguesa.destroy
    head :ok
  end

  def add_ingrediente
    ingrediente = Ingrediente.find(params[:ingrediente_id])
    hamburguesa = Hamburguesa.find(params[:hamburguesa_id])
    hamburguesa.ingredientes << ingrediente
    if hamburguesa.save
      respond_with hamburguesa, status: :created
    else
      respond_with hamburguesa.errors, status: :unprocessable_entity
    end
  end

  def delete_ingrediente
    ingrediente = Ingrediente.find(params[:ingrediente_id])
    hamburguesa = Hamburguesa.find(params[:hamburguesa_id])
    hamburguesa.ingredientes.delete(ingrediente)
    if hamburguesa.save
      respond_with hamburguesa, status: :ok
    else
      respond_with hamburguesa.errors, status: :unprocessable_entity
    end
  end

  private
    def set_hamburguesa
      @hamburguesa = Hamburguesa.find(params[:id])
    end

    def hamburguesa_params
      params.require(:hamburguesa).permit(:nombre, :descripcion, :imagen, :precio)
    end
end

app/controllers/ingredientes_controller.rb
class IngredientesController < ApplicationController
  before_action :set_ingrediente, only: [:show, :update, :destroy]

  def index
    @ingredientes = Ingrediente.all
    respond_with @ingredientes
  end

  def show
    respond_with @ingrediente
  end

  def create
    @ingrediente = Ingrediente.new(ingrediente_params)
    if @ingrediente.save
      respond_with @ingrediente, status: :created
    else
      respond_with @ingrediente.errors, status: :unprocessable_entity
    end
  end

  def update
    if @ingrediente.update(hamburguesa_params)
      respond_with @ingrediente, status: :ok
    else
      respond_with @ingrediente.errors, status: :unprocessable_entity
    end
  end

  def destroy
    if @ingrediente.hamburguesas.empty?
      @ingrediente.destroy
      head :ok
    else
      respond_with @ingrediente, status: :conflict
    end
  end

  private
    def set_ingrediente
      @ingrediente = Ingrediente.find(params[:id])
    end

    def ingrediente_params
      params.require(:ingrediente).permit(:nombre, :descripcion)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hamburguesas_helper.rb
module HamburguesasHelper
end

app/helpers/ingredientes_helper.rb
module IngredientesHelper
end

app/views/hamburguesas/_form.html.erb
<%= form_with(model: hamburguesa, local: true) do |form| %>
  <% if hamburguesa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hamburguesa.errors.count, "error") %> prohibited this hamburguesa from being saved:</h2>

      <ul>
        <% hamburguesa.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>

  <div class="field">
    <%= form.label :imagen %>
    <%= form.text_field :imagen %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.text_field :precio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hamburguesas/edit.html.erb
<h1>Editing Hamburguesa</h1>

<%= render 'form', hamburguesa: @hamburguesa %>

<%= link_to 'Show', @hamburguesa %> |
<%= link_to 'Back', hamburguesas_path %>

app/views/hamburguesas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hamburguesas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Imagen</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hamburguesas.each do |hamburguesa| %>
      <tr>
        <td><%= hamburguesa.nombre %></td>
        <td><%= hamburguesa.descripcion %></td>
        <td><%= hamburguesa.imagen %></td>
        <td><%= hamburguesa.precio %></td>
        <td><%= link_to 'Show', hamburguesa %></td>
        <td><%= link_to 'Edit', edit_hamburguesa_path(hamburguesa) %></td>
        <td><%= link_to 'Destroy', hamburguesa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hamburguesa', new_hamburguesa_path %>

app/views/hamburguesas/new.html.erb
<h1>New Hamburguesa</h1>

<%= render 'form', hamburguesa: @hamburguesa %>

<%= link_to 'Back', hamburguesas_path %>

app/views/hamburguesas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @hamburguesa.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @hamburguesa.descripcion %>
</p>

<p>
  <strong>Imagen:</strong>
  <%= @hamburguesa.imagen %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @hamburguesa.precio %>
</p>

<%= link_to 'Edit', edit_hamburguesa_path(@hamburguesa) %> |
<%= link_to 'Back', hamburguesas_path %>

app/views/ingredientes/_form.html.erb
<%= form_with(model: ingrediente, local: true) do |form| %>
  <% if ingrediente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingrediente.errors.count, "error") %> prohibited this ingrediente from being saved:</h2>

      <ul>
        <% ingrediente.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredientes/edit.html.erb
<h1>Editing Ingrediente</h1>

<%= render 'form', ingrediente: @ingrediente %>

<%= link_to 'Show', @ingrediente %> |
<%= link_to 'Back', ingredientes_path %>

app/views/ingredientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredientes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredientes.each do |ingrediente| %>
      <tr>
        <td><%= ingrediente.nombre %></td>
        <td><%= ingrediente.descripcion %></td>
        <td><%= link_to 'Show', ingrediente %></td>
        <td><%= link_to 'Edit', edit_ingrediente_path(ingrediente) %></td>
        <td><%= link_to 'Destroy', ingrediente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingrediente', new_ingrediente_path %>

app/views/ingredientes/new.html.erb
<h1>New Ingrediente</h1>

<%= render 'form', ingrediente: @ingrediente %>

<%= link_to 'Back', ingredientes_path %>

app/views/ingredientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @ingrediente.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @ingrediente.descripcion %>
</p>

<%= link_to 'Edit', edit_ingrediente_path(@ingrediente) %> |
<%= link_to 'Back', ingredientes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Iic3103T2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>